version: '3.8'

services:
  water-treatment-tools:
    build: .
    image: water-treatment-tools:latest
    container_name: water-treatment-tools
    restart: unless-stopped
    ports:
      - "6767:80"   # Web interface
      - "3001:3001" # API server
    environment:
      - TZ=America/New_York  # Adjust to your timezone
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.water-treatment.rule=Host(`water-treatment.yourdomain.com`)"
      - "traefik.http.routers.water-treatment.tls=true"
      - "traefik.http.routers.water-treatment.tls.certresolver=letsencrypt"
      - "traefik.http.services.water-treatment.loadbalancer.server.port=80"
    volumes:
      # Optional: Mount a volume for data persistence if needed
      - ./data:/usr/share/nginx/html/data:ro
      # BGG collection data persistence
      - bgg_collections:/app/api/data
    networks:
      - cerberusnet

  # Auto-updater service that pulls latest from GitHub
  watchtower:
    image: containrrr/watchtower:latest
    container_name: water-treatment-watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - cerberusnet

volumes:
  bgg_collections:
    driver: local

networks:
  cerberusnet:
    external: true

# Alternative compose file for simple local deployment
---
# docker-compose.local.yml
version: '3.8'

services:
  water-treatment-tools:
    build: .
    container_name: water-treatment-tools-local
    restart: unless-stopped
    ports:
      - "6767:80"   # Web interface
      - "3001:3001" # API server
    environment:
      - TZ=America/New_York
      - NODE_ENV=production
    volumes:
      - ./data:/usr/share/nginx/html/data:ro
      - bgg_collections_local:/app/api/data
    networks:
      - cerberusnet

volumes:
  bgg_collections_local:
    driver: local

networks:
  cerberusnet:
    external: true