
services:
  water-treatment-tools:
    build: .
    image: water-treatment-tools:latest
    container_name: water-treatment-tools
    restart: unless-stopped
    ports:
      - "6767:80"   # Web interface
      - "6768:3001" # Claude proxy API
    environment:
      - TZ=America/New_York  # Adjust to your timezone
      - NODE_ENV=production
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}  # Set this in .env file
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.water-treatment.rule=Host(`water-treatment.yourdomain.com`)"
      - "traefik.http.routers.water-treatment.tls=true"
      - "traefik.http.routers.water-treatment.tls.certresolver=letsencrypt"
      - "traefik.http.services.water-treatment.loadbalancer.server.port=80"
    volumes:
      # Mount sample data for the apps
      - ./sample-data:/usr/share/nginx/html/sample-data:ro
      # Mount .env file if it exists (optional - environment variables take precedence)
      - ./.env:/app/.env:ro
    networks:
      - cerberusnet

  # Auto-updater service that pulls latest from GitHub
  watchtower:
    image: containrrr/watchtower:latest
    container_name: water-treatment-watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - cerberusnet

networks:
  cerberusnet:
    external: true

# Alternative compose file for simple local deployment
---
# docker-compose.local.yml

services:
  water-treatment-tools:
    build: .
    container_name: water-treatment-tools-local
    restart: unless-stopped
    ports:
      - "6767:80"   # Web interface
      - "6768:3001" # Claude proxy API
    environment:
      - TZ=America/New_York
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}  # Set this in .env file
    volumes:
      - ./sample-data:/usr/share/nginx/html/sample-data:ro
      # Mount .env file if it exists (optional - environment variables take precedence)
      - ./.env:/app/.env:ro
    networks:
      - cerberusnet

networks:
  cerberusnet:
    external: true